name: CI - build and test

on:
  push:
     branches: [ main ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java version: '11'
        ditribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      working-directory: ./flatImitation
      run: ./gradlew build
    - name: Test
      working-directory: ./flatImitation
      run: ./gradlew test

